config/routes.rb
Twiteme::Application.routes.draw do
  resources :pictures
  root :to => "pictures#index"
  resources :users, :only => [ :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/picture.rb
class Picture
  include Mongoid::Document
  attr_accessible  :name, :image, :desc
  field :name, :type => String
  field :desc, :type => String
  field :image
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, :type => String
  field :uid, :type => String
  field :name, :type => String
  field :email, :type => String
  field :image_url, :type => String
  field :admin, :type => Boolean
  attr_accessible :provider, :uid, :name, :email, :image_url

  has_many :posts

  validates_uniqueness_of :email
  validates_format_of     :email, :with => /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i,
    :message => "must_be_a_valid_email_address"

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.image_url = auth['info']['image'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

    def facebook_user
    (session[:fb_access_token] && session[:fb_user_uid]) ? FBGraph::Client.new(:client_id => '313753795376894', :secret_id => '2279bc791147477e77d887ef481be128', :token => session[:fb_access_token]).selection.me.info! : nil
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    #render :text => params.inspect;return
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        post_on_facebook(@picture.id)
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  def post_on_facebook(id)
    @picture = Picture.find(id)
    client = FBGraph::Client.new(:client_id => '326792767407844', :secret_id => 'b596abda8297948894ec22022d596ab0', :token => session[:fb_access_token])
          user = client.selection.me.info!
          client.selection.user(user[:id]).feed.publish!(
            :message => "#{params[:picture][:desc]}", 
            :picture => 'http://localhost:3000/'+ @picture.image_url,
            :name => 'test name')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    token = auth['credentials']['token']
    session[:fb_access_token] = token
    session[:fbgraph_uid] = auth['uid']
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url
    end

  end

  def destroy
    reset_session
    redirect_to root_url
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?

  def index
    @users = User.paginate(:page => params[:page])
  end

    def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Task-Photo-Facebook", root_path, :class => 'brand'
%ul{:class => 'nav pull-right'} 
  - if user_signed_in?
    -if current_user.admin?
      %li  
        = link_to('people', home_people_path)
    %li
      = link_to (image_tag("#{current_user.image_url}", :size => '20x20'))
    %li
      = link_to (current_user.name)
    %li
      = link_to('Logout', signout_path)
  - else
    %li
      = link_to('Login', signin_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => " initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Tast-Photo-Facebook"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/pictures/_form.html.haml
= simple_form_for(@picture) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.text_area :desc
    %br
    = f.file_field :image
  .form-actions
    = f.button :submit

app/views/pictures/edit.html.haml
%h1 Editing picture

= render 'form'

= link_to 'Show', @picture
\|
= link_to 'Back', pictures_path

app/views/pictures/index.html.haml
%h1 Listing pictures

%table
  %tr
    %th Name
    %th Desc
    %th
    %th
    %th

  - @pictures.each do |picture|
    %tr
      %td= picture.name
      %td= picture.desc
      %td= link_to 'Show', picture
      %td= link_to 'Edit', edit_picture_path(picture)
      %td= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Picture', new_picture_path

app/views/pictures/new.html.haml
%h1 New picture

= render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @picture.name
%p
  %b Desc:
  = @picture.desc

= link_to 'Edit', edit_picture_path(@picture)
\|
= link_to 'Back', pictures_path

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/index.html.haml
%h2 Users
- @users.each do |user|
  %br/
  #{link_to user.email, user} signed up #{user.created_at.to_date}

= will_paginate

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}